#!/usr/bin/env bash
switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

hydrate() {
    if [ -f $2/.tmux-ready ]; then
        tmux send-keys -t $1 "source $2/.tmux-ready" ^M
    elif [ -f $HOME/.tmux-ready ]; then
        tmux send-keys -t $1 "source $HOME/.tmux-ready" ^M
    fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ ~/.config/nvim/ ~/go/src ~/projects /mnt/c/Users/downe /mnt/c/Users/downe/Lexicon/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr ":., " "____")
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    hydrate $selected_name $selected
    exit 0
fi

if ! tmux has_session $selected_name; then
    tmux new-session -ds $selected_name -c $selected
    hydrate $selected_name $selected
fi

switch_to $selected_name
